# Generated by Django 3.2.6 on 2021-08-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=50)),
                ('tweet_datetime', models.DateTimeField(auto_now=True)),
                ('tweet_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poormanstwitterapp.tweetauthor')),
            ],
            options={
                'verbose_name_plural': 'tweets',
            },
        ),
    ]
