# Generated by Django 3.2.6 on 2021-08-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poormanstwitterapp', '0003_alter_tweet_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date_time_formatted',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
