# Generated by Django 3.2.6 on 2021-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poormanstwitterapp', '0004_tweet_date_time_formatted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_time_formatted',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
