# Generated by Django 3.2.6 on 2021-08-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poormanstwitterapp', '0005_alter_tweet_date_time_formatted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date_time_formatted',
        ),
        migrations.AddField(
            model_name='tweet',
            name='formatted_date_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
